### PR TITLE
Now can load 3Ds Max Design 2013 .obj files

### PR DESCRIPTION
**Pull request by mitkonikov**
I had a problem loading 3Ds Max Design 2013 .obj files, because there were additional not needed spaces. I am removing them with TestingNull function. Just check the changes with your samples. Main works. Thanks.

### CODE REVIEW

**Comment by giawa** [comment]
Hi mitkonikov,

Thanks for the pull request - can you please provide a sample .obj file that requires this code?  Thanks

**Comment by mitkonikov** [comment]
Hi, here is a link from one obj that I personally exported from 3Ds Max Design 2013. I dont have objs from the internet that are from 3Ds Max Design 2013, but you can find if you want. Link : https://www.dropbox.com/s/gsxs67uqmwmi11u/OBJ%20from%203Ds%20Max%20Design%202013.rar?dl=0

**Comment by mitkonikov** [comment]
Hi, here is a obj that I done in 3Ds Max, Its with a Today's Date, just for verification. When generating Text from plugin in 3Ds Max I could not exported it, some problem with faces, but I made it from Boxes. It requires the new code. Link : https://www.dropbox.com/s/bxck2l2fye32kmu/TextDate.rar?dl=0

**Comment by mitkonikov** [comment]
https://www.youtube.com/watch?v=q5C23_KeaKw here is a video that I made, and in this video is a proof that I am using 3Ds Max 2013

**Comment by giawa** [comment]
Hi mitkonikov,

Thanks for all of the links and files.  I was away all weekend camping but am now back, I'll be checking out these files and the pull request tonight.

**Comment by mitkonikov** [comment]
I don't understand why its says that there are so much changes, I just added few lines of code I think. I'll make another pull request just to clear out this problem. Thanks

**Comment by giawa** [comment]
Closing request due to conflicts

**Pull request closed without merging**
